
export const CHANGE_CURRENT_BOOKID = 'CHANGE_CURRENT_BOOKID';
export const UPDATE_USERINFO = 'UPDATE_USERINFO';
export const CHANGE_USEREMAIL = 'CHANGE_USEREMAIL';
export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const CHANGE_EDIT_BOOK_STATUS = 'CHANGE_EDIT_BOOK_STATUS';
export const CHANGE_EDIT_BOOK_ID = 'CHANGE_EDIT_BOOK_ID';
export const CHANGE_EDIT_AUTHOR_STATUS = 'CHANGE_EDIT_AUTHOR_STATUS';
export const CHANGE_EDIT_AUTHOR_ID = 'CHANGE_EDIT_AUTHOR_ID';
